# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 6558dd6e7175305dd935b3c98b21cc5a690161a8c9d423db6ad547c94f0f0826540a474e9f7c65dece5f2cc20bb1956cd9b56af2af315067174f1360bcaf459b

test:
  secret_key_base: caf3eb0904c65f9ed679dbbc06a0d3eb292a66cc889e5214d1411124795567d23edaae2e620d5f0067bbd1a35b1225ab53d687fa31c6b9e3f4928d59c0cb4939

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
